DROP TABLE ORDER_MANAGEMENT_ORDER_ITEM_DETAILS IF EXISTS;
create table ORDER_MANAGEMENT_ORDER_ITEM_DETAILS(
ORDER_MANAGEMENT_ORDER_ITEM_DETAILS_ID INT NOT NULL AUTO_INCREMENT,PRODUCT_CODE INTEGER,
PRODUCT_NAME VARCHAR(800), QUANTITY INTEGER );



DROP TABLE ORDER_MANAGEMENT_ORDER_DETAILS IF EXISTS;

create table ORDER_MANAGEMENT_ORDER_DETAILS(
ORDER_MANAGEMENT_ORDER_DETAILS_ID INT NOT NULL AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(500),ORDER_DATE TIMESTAMP,SHIPPING_ADDRESS VARCHAR(800), 
ORDER_MANAGEMENT_ORDER_ITEM_DETAILS_ID INTEGER,TOTAL_AMT INTEGER );


insert into ORDER_MANAGEMENT_ORDER_ITEM_DETAILS(PRODUCT_NAME,PRODUCT_CODE,QUANTITY) values ('testProduct',456,5);

INSERT INTO ORDER_MANAGEMENT_ORDER_DETAILS(
CUSTOMER_NAME,SHIPPING_ADDRESS,ORDER_MANAGEMENT_ORDER_ITEM_DETAILS_ID,TOTAL_AMT) 
VALUES ('customerABC','CHENGICHARLA,HYDERBAD-10',1,56);
